.TH RPEO 6 2013-04-16

.SH NAME
\fBrpeo\fP \- Humorous typo-based git runner; drives a car over the terminal.

.SH DESCRIPTION
\fBrpeo\fP is intended to catch accidental typos of 'rpeo' instead of 'repo'. It
displays an animation of a car driving by, and then launches git. Any
parameters or arguments given to \fBrpeo\fP will be passed through to repo.

The car image is derived from the look of an old VW Golf GTI.

.SH SEE ALSO
\fBgti \fP(1), \fBsl\fP(6)

.SH AUTHOR
\fBrpeo\fP was written by Alvaro Moran <alvaro.moran@gmail.com>, but the code
has been heavily taken from gti.
